site_name: "Mosqlimate client"
site_description: "Client library for the Mosqlimate project data platform."
site_url: "https://Mosqlimate-project.github.io/mosqlimate-client"
repo_url: "https://github.com/Mosqlimate-project/mosqlimate-client"
repo_name: "Mosqlimate-project/mosqlimate-client"

nav:
    - Home:
        - Overview: 'index.md'
        - Changelog: 'changelog.md'
        - Credits: 'credits.md'
        - License: 'license.md'
    - Tutorials:
        - Datastore: 'tutorials/API/datastore.ipynb'
        - Registry: 'tutorials/API/registry.ipynb'
        - Using from R: 'tutorials/Using Mosqlient from R.ipynb'
        - Model Scoring: 'tutorials/scoring.ipynb'
        - Simple forecast model: 'tutorials/baseline_model.ipynb'
        - Ensemble predictions: 'tutorials/ensemble.ipynb'
    - Code Reference:
        - Infodengue data: 'reference/infodengue.md'
        - Climate data: 'reference/climate.md'
        - Get authors: 'reference/authors.md'
        - Get, post and delete models: 'reference/models.md'
        - Get, post and delete predictions: 'reference/predictions.md'
        - Score: 'reference/score.md'
        - Baseline Arima: 'reference/baseline.md'
        - Ensemble: 'reference/ensemble.md'
        - Prediction optimize: 'reference/pred_opt.md'


    - Development:
        - Contributing: 'contributing.md'
        - Code of Conduct: 'code_of_conduct.md'
        - Coverage report: 'coverage.md'

theme:
  name: material
  features:
  - navigation.tabs
  palette:
    scheme: slate
    primary: teal
    accent: purple

extra_css:
- css/mkdocstrings.css

markdown_extensions:
- admonition
- pymdownx.emoji
- pymdownx.magiclink
- pymdownx.snippets:
    check_paths: true
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.tasklist
- toc:
    permalink: true

plugins:
    - search
    - mkdocs-jupyter:
        include: ["tutorials/**/*.ipynb", "tutorials/*.ipynb"]
        include_requirejs: true
        custom_mathjax_url: "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_CHTML-full,Safe"

    - coverage:
        html_report_dir: build/coverage
    - mkdocstrings:
    - macros:
        module_name: docs/macros
