# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: release

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 20

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        submodules: recursive

    - uses: conda-incubator/setup-miniconda@v3
      with:
        miniforge-version: latest
        environment-file: conda/base.yaml
        channels: conda-forge,nodefaults
        activate-environment: mosqlient
        auto-update-conda: true
        conda-solver: libmamba

    - uses: actions/setup-node@v3
      with:
        node-version: 20.11.0

    - name: Validate PR commits with commitlint
      if: github.event_name == 'pull_request'
      run: |
        npm install --no-save @commitlint/config-conventional &&
        npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

    - name: Run semantic release (for tests)
      if: ${{ github.event_name != 'workflow_dispatch' }}
      run: |
        npx --yes \
        -p semantic-release \
        -p "@semantic-release/commit-analyzer" \
        -p "@semantic-release/release-notes-generator" \
        -p "@semantic-release/changelog" \
        -p "@semantic-release/exec" \
        -p "@semantic-release/github" \
        -p "@semantic-release/git" \
        -p "semantic-release-replace-plugin@1.2.7" \
        semantic-release --dry-run

    - name: Run semantic release
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        poetry config pypi-token.pypi ${PYPI_TOKEN}
        npx --yes \
        -p semantic-release \
        -p "@semantic-release/commit-analyzer" \
        -p "@semantic-release/release-notes-generator" \
        -p "@semantic-release/changelog" \
        -p "@semantic-release/exec" \
        -p "@semantic-release/github" \
        -p "@semantic-release/git" \
        -p "semantic-release-replace-plugin@1.2.7" \
        semantic-release --ci --debug
